// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Social_Media_Activity_Feed.Data.Migrations
{
    [DbContext(typeof(SocialMediaDataContext))]
    [Migration("20260221064550_AddedHalfOfTheSelfReferencingTables")]
    partial class AddedHalfOfTheSelfReferencingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("BlockedAccount", b =>
                {
                    b.Property<long>("BlockingUserID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlockedAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlockingUserID", "BlockedAccountId");

                    b.HasIndex("BlockedAccountId", "BlockingUserID");

                    b.ToTable("Blocked_Accounts");
                });

            modelBuilder.Entity("CloseFriend", b =>
                {
                    b.Property<long>("AddingUserID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CloseFriendAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AddingUserID", "CloseFriendAccountId");

                    b.HasIndex("CloseFriendAccountId", "AddingUserID");

                    b.ToTable("Close_Friends");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.Property<long>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("CommenterID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PostID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommentID");

                    b.HasIndex("CommenterID");

                    b.HasIndex("PostID")
                        .IsUnique();

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Follow", b =>
                {
                    b.Property<long>("FollowerID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FollowedID")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowerID", "FollowedID");

                    b.HasIndex("FollowedID", "FollowerID");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.Property<long>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<long>("InitiatorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostID");

                    b.HasIndex("InitiatorID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("PostLike", b =>
                {
                    b.Property<long>("PostLikeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("LikerID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PostID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostLikeID");

                    b.HasIndex("LikerID");

                    b.HasIndex("PostID", "LikerID")
                        .IsUnique();

                    b.ToTable("Post_Likes");
                });

            modelBuilder.Entity("PostMedia", b =>
                {
                    b.Property<long>("PostID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostID");

                    b.ToTable("Post_Media_Links");
                });

            modelBuilder.Entity("SavedPost", b =>
                {
                    b.Property<long>("SaverID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PostID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SaverID", "PostID");

                    b.HasIndex("PostID", "SaverID");

                    b.ToTable("Saved_Posts");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImage_MediaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserProfile", b =>
                {
                    b.Property<long>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccountPrivacy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("User_Profiles");
                });

            modelBuilder.Entity("BlockedAccount", b =>
                {
                    b.HasOne("User", "Blocked_Account")
                        .WithMany("AccountBlockedBy")
                        .HasForeignKey("BlockedAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "BlockingUser")
                        .WithMany("BlockedAccounts")
                        .HasForeignKey("BlockingUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blocked_Account");

                    b.Navigation("BlockingUser");
                });

            modelBuilder.Entity("CloseFriend", b =>
                {
                    b.HasOne("User", "AddingUser")
                        .WithMany("AddedCloseFriends")
                        .HasForeignKey("AddingUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "CloseFriendAccount")
                        .WithMany("AddedAsCloseFriendBy")
                        .HasForeignKey("CloseFriendAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddingUser");

                    b.Navigation("CloseFriendAccount");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasOne("User", "Commenter")
                        .WithMany()
                        .HasForeignKey("CommenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commenter");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Follow", b =>
                {
                    b.HasOne("User", "Followed")
                        .WithMany("FollowedAccounts")
                        .HasForeignKey("FollowedID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Follower")
                        .WithMany("FollowingAccounts")
                        .HasForeignKey("FollowerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.HasOne("User", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiator");
                });

            modelBuilder.Entity("PostLike", b =>
                {
                    b.HasOne("User", "Liker")
                        .WithMany()
                        .HasForeignKey("LikerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liker");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PostMedia", b =>
                {
                    b.HasOne("Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SavedPost", b =>
                {
                    b.HasOne("Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Saver")
                        .WithMany()
                        .HasForeignKey("SaverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Saver");
                });

            modelBuilder.Entity("UserProfile", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("UserProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("AccountBlockedBy");

                    b.Navigation("AddedAsCloseFriendBy");

                    b.Navigation("AddedCloseFriends");

                    b.Navigation("BlockedAccounts");

                    b.Navigation("FollowedAccounts");

                    b.Navigation("FollowingAccounts");

                    b.Navigation("UserProfile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
