// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Social_Media_Activity_Feed.Data.Migrations
{
    [DbContext(typeof(SocialMediaDataContext))]
    [Migration("20260222053534_StoppedAtTPHNotifications")]
    partial class StoppedAtTPHNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("BlockedAccount", b =>
                {
                    b.Property<long>("BlockingUserID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BlockedAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BlockingUserID", "BlockedAccountId");

                    b.HasIndex("BlockedAccountId", "BlockingUserID");

                    b.ToTable("Blocked_Accounts");
                });

            modelBuilder.Entity("CloseFriend", b =>
                {
                    b.Property<long>("AddingUserID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CloseFriendAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AddingUserID", "CloseFriendAccountId");

                    b.HasIndex("CloseFriendAccountId", "AddingUserID");

                    b.ToTable("Close_Friends");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.Property<long>("PostID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("CommenterID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LikeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostID");

                    b.HasIndex("CommenterID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FeedContent", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FollowedID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FollowerID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PostID")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserID");

                    b.HasIndex("FollowedID");

                    b.HasIndex("PostID");

                    b.HasIndex("FollowerID", "FollowedID")
                        .IsUnique();

                    b.ToTable("Feed_Contents");
                });

            modelBuilder.Entity("Follow", b =>
                {
                    b.Property<long>("FollowerID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FollowedID")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowerID", "FollowedID");

                    b.HasIndex("FollowedID", "FollowerID");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Property<long>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReceiptientID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SenderID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MessageID");

                    b.HasIndex("ReceiptientID", "SenderID");

                    b.HasIndex("SenderID", "ReceiptientID")
                        .IsUnique();

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MessageMedia", b =>
                {
                    b.Property<long>("MessageID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MessageID");

                    b.ToTable("Message_Media_Links");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.Property<long>("ReceivingUserID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InitaiatorID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("NotificationType")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReceivingUserID", "InitaiatorID");

                    b.HasIndex("InitaiatorID");

                    b.HasIndex("NotificationType");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.Property<long>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("InitiatorID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikeCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostID");

                    b.HasIndex("InitiatorID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("PostLike", b =>
                {
                    b.Property<long>("LikerID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PostID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("LikerID", "PostID");

                    b.HasIndex("PostID");

                    b.ToTable("Post_Likes");
                });

            modelBuilder.Entity("PostMedia", b =>
                {
                    b.Property<long>("PostID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostID");

                    b.ToTable("Post_Media_Links");
                });

            modelBuilder.Entity("SavedPost", b =>
                {
                    b.Property<long>("SaverID")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PostID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SaverID", "PostID");

                    b.HasIndex("PostID", "SaverID");

                    b.ToTable("Saved_Posts");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("FollowersCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FollowingCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImage_MediaUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserProfile", b =>
                {
                    b.Property<long>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccountPrivacy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Verified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("User_Profiles");
                });

            modelBuilder.Entity("BlockedAccount", b =>
                {
                    b.HasOne("User", "Blocked_Account")
                        .WithMany("AccountBlockedBy")
                        .HasForeignKey("BlockedAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "BlockingUser")
                        .WithMany("BlockedAccounts")
                        .HasForeignKey("BlockingUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Blocked_Account");

                    b.Navigation("BlockingUser");
                });

            modelBuilder.Entity("CloseFriend", b =>
                {
                    b.HasOne("User", "AddingUser")
                        .WithMany("AddedCloseFriends")
                        .HasForeignKey("AddingUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "CloseFriendAccount")
                        .WithMany("AddedAsCloseFriendBy")
                        .HasForeignKey("CloseFriendAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddingUser");

                    b.Navigation("CloseFriendAccount");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasOne("User", "Commenter")
                        .WithMany("UserComments")
                        .HasForeignKey("CommenterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commenter");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("FeedContent", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("FeedContents")
                        .HasForeignKey("FollowedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Post", "Post")
                        .WithMany("Feed")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Follow", b =>
                {
                    b.HasOne("User", "Followed")
                        .WithMany("FollowedAccounts")
                        .HasForeignKey("FollowedID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Follower")
                        .WithMany("FollowingAccounts")
                        .HasForeignKey("FollowerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Followed");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.HasOne("User", "Receiptient")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("ReceiptientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiptient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MessageMedia", b =>
                {
                    b.HasOne("Message", "Message")
                        .WithMany("MessageMedia")
                        .HasForeignKey("MessageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Notification", b =>
                {
                    b.HasOne("User", "Initaiator")
                        .WithMany("NotificationsSent")
                        .HasForeignKey("InitaiatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "ReceivingUser")
                        .WithMany("NotificationsReceived")
                        .HasForeignKey("ReceivingUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initaiator");

                    b.Navigation("ReceivingUser");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.HasOne("User", "Initiator")
                        .WithMany("UserPosts")
                        .HasForeignKey("InitiatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiator");
                });

            modelBuilder.Entity("PostLike", b =>
                {
                    b.HasOne("User", "Liker")
                        .WithMany("UserLikedPosts")
                        .HasForeignKey("LikerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liker");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("PostMedia", b =>
                {
                    b.HasOne("Post", "Post")
                        .WithMany("PostMediasLinks")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SavedPost", b =>
                {
                    b.HasOne("Post", "Post")
                        .WithMany("Saves")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "Saver")
                        .WithMany("UserSavedPosts")
                        .HasForeignKey("SaverID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Saver");
                });

            modelBuilder.Entity("UserProfile", b =>
                {
                    b.HasOne("User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("UserProfile", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Message", b =>
                {
                    b.Navigation("MessageMedia");
                });

            modelBuilder.Entity("Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Feed");

                    b.Navigation("PostLikes");

                    b.Navigation("PostMediasLinks");

                    b.Navigation("Saves");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("AccountBlockedBy");

                    b.Navigation("AddedAsCloseFriendBy");

                    b.Navigation("AddedCloseFriends");

                    b.Navigation("BlockedAccounts");

                    b.Navigation("FeedContents");

                    b.Navigation("FollowedAccounts");

                    b.Navigation("FollowingAccounts");

                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("NotificationsReceived");

                    b.Navigation("NotificationsSent");

                    b.Navigation("UserComments");

                    b.Navigation("UserLikedPosts");

                    b.Navigation("UserPosts");

                    b.Navigation("UserProfile")
                        .IsRequired();

                    b.Navigation("UserSavedPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
